// AutoGenerated File


export class AddInventoryDto {

    productId: number;

    amount: number;

    /** Initializes a new instance of the AddInventoryDto class **/
    public constructor(init?: Partial<AddInventoryDto>) {
        Object.assign(this, init);
    }
}
