// AutoGenerated File

import { ProfileDto } from './ProfileDto';

export class AdminProfileDto extends ProfileDto {

    adminNotes: string;

    /** Initializes a new instance of the AdminProfileDto class **/
    public constructor(init?: Partial<AdminProfileDto>) {
        super(init);
    }
}
