// AutoGenerated File


export class AllNeedsSummaryDto {

    needsMet: number;

    outstandingNeeds: number;

    /** Initializes a new instance of the AllNeedsSummaryDto class **/
    public constructor(init?: Partial<AllNeedsSummaryDto>) {
        Object.assign(this, init);
    }
}
