// AutoGenerated File


export class EditInventoryDto {

    productId: number;

    newAmount: number;

    /** Initializes a new instance of the EditInventoryDto class **/
    public constructor(init?: Partial<EditInventoryDto>) {
        Object.assign(this, init);
    }
}
