// AutoGenerated File

/** Data transfer object for equipment */
export class EquipmentDto {

    /** Gets or sets the identifier. */
    id: number;

    /** Gets or sets the name. */
    name: string;

    /** Gets or sets the description. */
    description: string;

    /** Initializes a new instance of the EquipmentDto class **/
    public constructor(init?: Partial<EquipmentDto>) {
        Object.assign(this, init);
    }
}
