// AutoGenerated File

import { FeedbackType } from './FeedbackType';

/** Model class representing user feedback. */
export class FeedbackDto {

    /** Gets or sets the identifier. */
    id: number;

    /** Gets or sets the type of feedback this is meant to indicate. */
    type: FeedbackType;

    /** Gets or sets the comment the user has submitted. */
    comment: string;

    /** Gets or sets the URL of the page the user submitted the feedback from. */
    url: string;

    submittedBy: string;

    createdDate: Date;

    /** Initializes a new instance of the FeedbackDto class **/
    public constructor(init?: Partial<FeedbackDto>) {
        Object.assign(this, init);
    }
}
