// AutoGenerated File

import { ProductDto } from './ProductDto';

export class InventoryTransactionDto {

    product: ProductDto;

    amount: number;

    /** Initializes a new instance of the InventoryTransactionDto class **/
    public constructor(init?: Partial<InventoryTransactionDto>) {
        Object.assign(this, init);
    }
}
