// AutoGenerated File


export class MakerStockDto {

    id: number;

    makerId: number;

    productId: number;

    productName: string;

    quantity: number;

    updatedOn: Date;

    /** Initializes a new instance of the MakerStockDto class **/
    public constructor(init?: Partial<MakerStockDto>) {
        Object.assign(this, init);
    }
}
