// AutoGenerated File


export class NeedLookupDto {

    needId: number;

    productId: number;

    profileDisplayName: string;

    outstandingQuantity: number;

    dueDate: Date;

    /** Initializes a new instance of the NeedLookupDto class **/
    public constructor(init?: Partial<NeedLookupDto>) {
        Object.assign(this, init);
    }
}
