// AutoGenerated File

/** Model class representing a need for PPE */
export class NeedDto {

    /** Gets or sets the identifier for the need. */
    id: number;

    /** Gets or sets the profile identifier. */
    profileId: number;

    /** Gets or sets the date the need was created on. */
    createdDate: Date;

    /** Gets or sets the date the need requests to be fulfilled by. */
    dueDate: Date;

    /** Gets or sets the date the need was fulfilled on. */
    fulfilledDate: Date;

    /** Gets or sets the product identifier. */
    productId: number;

    /** Gets or sets the quantity. */
    quantity: number;

    /** Gets a value indicating whether this instance is overdue. */
    isOverdue: boolean;

    outstandingQuantity: number;

    /** Gets or sets any special instructions tied to the Need. */
    specialInstructions: string;

    /** Initializes a new instance of the NeedDto class **/
    public constructor(init?: Partial<NeedDto>) {
        Object.assign(this, init);
    }
}
