// AutoGenerated File

import { ProductDto } from './ProductDto';

/** Model class representing a type or category of products. */
export class ProductTypeDto {

    /** Gets or sets the identifier for this product type. */
    id: number;

    /** Gets or sets the name of this product type. */
    name: string;

    sortOrder: number;

    /** Gets or sets the products for this product type. */
    products: ProductDto[];

    /** Initializes a new instance of the ProductTypeDto class **/
    public constructor(init?: Partial<ProductTypeDto>) {
        Object.assign(this, init);
    }
}
