// AutoGenerated File


export class ProductDto {

    id: number;

    name: string;

    description: string;

    instructionUrl: string;

    isDeprecated: boolean;

    imageUrl: string;

    /** Initializes a new instance of the ProductDto class **/
    public constructor(init?: Partial<ProductDto>) {
        Object.assign(this, init);
    }
}
