// AutoGenerated File


export class ProfileDto {

    id: number;

    firstName: string;

    lastName: string;

    bio: string;

    phone: string;

    email: string;

    address: string;

    city: string;

    state: string;

    isSelfQuarantined: boolean;

    createdDate: Date;

    zipCode: string;

    isDropOffPoint: boolean;

    displayName: string;

    /** Initializes a new instance of the ProfileDto class **/
    public constructor(init?: Partial<ProfileDto>) {
        Object.assign(this, init);
    }
}
