// AutoGenerated File


export class UpdateProfileDto {

    id: number;

    companyName: string;

    firstName: string;

    lastName: string;

    bio: string;

    phone: string;

    email: string;

    address: string;

    address2: string;

    city: string;

    state: string;

    isSelfQuarantined: boolean;

    zipCode: string;

    isDropOffPoint: boolean;

    isSupplier: boolean;

    isRequestor: boolean;

    hasCadSkills: boolean;

    adminNotes: string;

    /** Gets or sets a value indicating whether this user has gone through the new onboarding process. */
    hasOnboarded: boolean;

    /** Initializes a new instance of the UpdateProfileDto class **/
    public constructor(init?: Partial<UpdateProfileDto>) {
        Object.assign(this, init);
    }
}
